<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="9.3.3" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" Version="10.4.0" />
    <PackageReference Include="Testcontainers.Elasticsearch" Version="4.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Foundatio.Lucene.Elasticsearch\Foundatio.Lucene.Elasticsearch.csproj" />
  </ItemGroup>

</Project>
